name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Next.js
        run: npm run build

      - name: Install prod dependencies
        run: npm ci --omit=dev --ignore-scripts --legacy-peer-deps

      - name: Prepare production env file
        run: |
          cat <<EOF > .env.production
          NEXT_PUBLIC_AUTH_API_URL=${{ secrets.AUTH_API_URL }}
          EOF

      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: '.next,public,package.json,package-lock.json,.env.production,node_modules'
          target: /home/ubuntu/frontend
          debug: true

      - name: SSH & deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/frontend

            # install Node if not already
            if ! command -v node >/dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # global PM2
            if ! command -v pm2 >/dev/null; then
              sudo npm install -g pm2
            fi

            # start or reload via PM2
            pm2 describe frontend || pm2 start npm --name frontend -- start
            pm2 reload frontend

            # persist PM2 on reboot
            pm2 save
            pm2 startup systemd -u ubuntu --hp /home/ubuntu
